import { z } from "zod";
import { CATEGORIES } from "./types";

const CategorySchema = z.enum(CATEGORIES);

const AttributesSchema = z.object({
  displacementCc: z.number().int().positive().lte(9000),
  forcedInduction: z.boolean(),
  seats: z.number().int().gte(1).lte(9),
  bodyStyle: z.enum([
    "sedan",
    "coupe",
    "hatchback",
    "wagon",
    "suv",
    "convertible",
    "truck",
    "sports",
  ]),
  sportsCarBased: z.boolean(),
});

export const CarSchema = z
  .object({
    id: z.string().regex(/^[a-z0-9-]+$/, "kebab-case ids only"),
    make: z.string().min(1),
    model: z.string().min(1),
    trim: z.string().min(1).optional(),
    yearStart: z.number().int().gte(1945).lte(2100),
    yearEnd: z.number().int().gte(1945).lte(2100),
    classes: z.record(CategorySchema, z.string().min(1)),
    attributes: AttributesSchema.optional(),
    streetExclusion: z.string().min(1).optional(),
    verified: z.boolean(),
    notes: z.string().optional(),
  })
  .refine((c) => c.yearEnd >= c.yearStart, {
    message: "yearEnd must be >= yearStart",
  })
  .refine((c) => c.classes.street !== undefined || c.streetExclusion !== undefined, {
    message:
      "every car needs a Street class, or a streetExclusion explaining why it has none",
  });

export const ModSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/, "kebab-case ids only"),
  label: z.string().min(1),
  group: z.enum([
    "tires-wheels",
    "suspension",
    "engine-drivetrain",
    "brakes",
    "body-aero",
    "interior-electrical",
  ]),
  minCategory: CategorySchema,
  ruleRef: z.string().min(1),
  note: z.string().optional(),
  verified: z.boolean(),
});

export const CarsFileSchema = z.array(CarSchema).superRefine((cars, ctx) => {
  const seen = new Set<string>();
  for (const car of cars) {
    if (seen.has(car.id)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: `duplicate car id: ${car.id}` });
    }
    seen.add(car.id);
  }
});

/** Tier-2 search data: raw Appendix A listings, generated by tools/build_listings.py. */
export const ListingSchema = z.object({
  id: z.string().regex(/^l\d{4}$/),
  category: CategorySchema,
  class: z.string().min(2).max(4),
  make: z.string().min(1),
  model: z.string().min(2),
  yearStart: z.number().int().optional(),
  yearEnd: z.number().int().optional(),
  makeSuspect: z.boolean().optional(),
  /** Set when this listing duplicates a curated cars.json row. */
  curatedId: z.string().optional(),
});

export const ListingsFileSchema = z.array(ListingSchema);

export type Listing = z.infer<typeof ListingSchema>;

export const ModsFileSchema = z.array(ModSchema).superRefine((mods, ctx) => {
  const seen = new Set<string>();
  for (const mod of mods) {
    if (seen.has(mod.id)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: `duplicate mod id: ${mod.id}` });
    }
    seen.add(mod.id);
  }
});
